[build]
  command = "npm install && npm run build"  # Added npm install
  publish = "dist"
  environment = { 
    NODE_VERSION = "20.9.0",  # Updated to exact required version
    CI = "true"  # Added CI flag
  }

[context.production.environment]
  NODE_ENV = "production"